version: '3'
services:          
  express:
    build: ./
    environment:
      - PORT=
      - BASE_URL=
      - MONGODB_URL=
      - JWT_SECRET_KEY=
      - GITHUB_CLIENT_ID=
      - GITHUB_CLIENT_SECRET=
      - ACCESSTOKEN_EXPIRE=
    container_name: express
    expose:
      - 4000
    restart: "unless-stopped"